language: csharp
mono:
  - latest
script:
  - mono .nuget/nuget.exe restore Sharding-pattern/ShardingTest.sln
  - xbuild /p:Configuration=Release Sharding-pattern/ShardingTest.sln
  - mono Sharding-pattern/bin/Release/ShardingTest.exe