language: csharp
mono:
  - latest
install:
 - travis_retry nuget restore Sharding-pattern/ShardingTest.sln
 - travis_retry nuget restore SignalR-example/SignalR-example.sln
script:
  - xbuild /p:Configuration=Release Sharding-pattern/ShardingTest.sln
  - mono Sharding-pattern/ShardingTest/bin/Release/ShardingTest.exe
  - xbuild /p:Configuration=Release SignalR-example/SignalR-example.sln
  - mono SignalR-example/SignalR-example/bin/Release/SignalR-example.dll